/*
 * Copyright (c) 2015 Cisco Systems, Inc.  All rights reserved.
 * Copyright (c) 2017      Intel, Inc.  All rights reserved.
 * Copyright (c) 2021-2026 Nanook Consulting.  All rights reserved.
 * $COPYRIGHT$
 *
 * Additional copyrights may follow
 *
 * $HEADER$
 */

#ifndef PMIX_PDL_LIBLTDL
#define PMIX_PDL_LIBLTDL

#include "src/include/pmix_config.h"

#include "src/mca/pdl/pdl.h"

#include <ltdl.h>

extern pmix_pdl_base_module_t pmix_pdl_plibltdl_module;

/*
 * Dynamic library handles generated by this component.
 *
 * If we're debugging, keep a copy of the name of the file we've opened.
 */
struct pmix_pdl_handle_t {
    lt_dlhandle ltdl_handle;
#if PMIX_ENABLE_DEBUG
    char *filename;
#endif
};

typedef struct {
    pmix_pdl_base_component_t base;

#if PMIX_PDL_PLIBLTDL_HAVE_LT_DLADVISE
    /* If the version of libltdl that we are compiling against has
       lt_dladvise, use it to support opening DSOs in a variety of
       modes. */
    lt_dladvise advise_private_noext;
    lt_dladvise advise_private_ext;
    lt_dladvise advise_public_noext;
    lt_dladvise advise_public_ext;
#endif
} pmix_pdl_plibltdl_component_t;

extern pmix_pdl_plibltdl_component_t pmix_mca_pdl_plibltdl_component;

#endif /* PMIX_PDL_LIBLTDL */
