# -*- makefile -*-
#
# Copyright (c) 2014-2020 Intel, Inc.  All rights reserved.
# Copyright (c) 2014      Artem Y. Polyakov <artpol84@gmail.com>.
#                         All rights reserved.
# Copyright (c) 2016      Cisco Systems, Inc.  All rights reserved.
# Copyright (c) 2024-2025 Nanook Consulting  All rights reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$
#

EXTRA_DIST += server/help-pmix-server.txt

headers += \
        server/pmix_server_ops.h

sources += \
        server/pmix_server.c \
        server/pmix_server_ops.c \
        server/pmix_server_registration.c \
        server/pmix_server_setup.c \
        server/pmix_server_dmodex.c \
        server/pmix_server_iof.c \
        server/pmix_server_inventory.c \
        server/pmix_server_pset.c \
        server/pmix_server_switchyard.c \
        server/pmix_server_op_replies.c \
        server/pmix_server_info_replies.c \
        server/pmix_server_get.c \
        server/pmix_server_group.c \
        server/pmix_server_fence.c \
        server/pmix_server_connect.c \
        server/pmix_server_resolve.c
