#!/usr/bin/env python3
#
# Copyright (c) 2020      Intel, Inc.  All rights reserved.
# Copyright (c) 2020-2022 Cisco Systems, Inc.  All rights reserved
# Copyright (c) 2021-2025 Nanook Consulting  All rights reserved.
# Copyright (c) 2022      Triad National Security, LLC. All rights reserved.
# $COPYRIGHT$
#
# Construct a dictionary for translating attributes to/from
# their defined name and their string representation - used
# by tools to interpret user input
#

import os
import sys
import argparse

# string form -> id for every attribute that currently exists.
#
# Keyed on the STRING, not the C name, because the string is the identity
# everything else uses: values are stored and looked up by it, so two
# names sharing a string are one attribute as far as the datastore is
# concerned and must share an id. That is the deliberate case for a
# deprecation rename - PMIX_ALLOC_NETWORK and PMIX_ALLOC_FABRIC are both
# "pmix.alloc.net" - and keying on the name instead would hand them
# separate ids and let array order decide which one a lookup found.
ids = {}
# id -> string for ids whose attribute has been removed. Retired ids are
# never handed out again: an id is a value two processes have to agree
# on, so reusing one makes an old peer resolve it to the wrong
# attribute. Same discipline as the PMIX_* status codes.
retired = {}
# string -> the C names that define it, for the map's third column
names = {}
# next id available for a brand new attribute
next_free = 0
# strings seen in this scan, in scan order
harvested = []
# whether an unknown name may be assigned an id (--update-ids)
assign_mode = False

RETIRED_PREFIX = "RETIRED:"

MAP_HEADER = """\
# PMIx attribute id map.
#
# Every attribute in include/pmix_common.h.in and include/pmix_deprecated.h
# has a numeric id, and THAT ID IS PART OF THE COMPATIBILITY SURFACE. Two
# processes built from different PMIx releases have to agree on it - the
# gds/shmem3 datastore stores keys by id in memory it shares with peers,
# so an id that means one attribute here and another there resolves to the
# wrong value rather than to an error.
#
# This file is what makes them agree. construct_dictionary.py reads it and
# assigns each attribute the id recorded here, so inserting an attribute in
# the middle of a header no longer renumbers everything after it. Ids were
# previously assigned by scan order, which is exactly what made them move.
#
# The rules:
#
#   * ids are append-only. A new attribute gets the next free id, at the
#     end, wherever it sits in the header.
#   * an id is never reused. An attribute that goes away keeps its id,
#     marked RETIRED: so the record of what owned it survives.
#   * this file is edited by the tool, not by hand:
#
#         make update-dictionary
#
#     then commit the result with the header change that prompted it. A
#     normal build will not assign ids - it fails and tells you to run
#     that - so two branches cannot silently hand out the same id.
#
# Sorted by id. Generated by construct_dictionary.py --update-ids.
"""


def load_id_map(path):
    """Read the id map. Returns 0 on success."""
    global next_free

    if not os.path.exists(path):
        print("ID MAP {path} NOT FOUND".format(path=path))
        return 1
    try:
        mapfile = open(path, "r")
        lines = mapfile.readlines()
        mapfile.close()
    except Exception as e:
        print("ID map {path} could not be read: {e}".format(path=path, e=e))
        return 1

    highest = -1
    for line in lines:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        tokens = line.split()
        if 2 > len(tokens):
            print("MALFORMED LINE IN {path}: {line}".format(path=path, line=line))
            return 1
        key = tokens[0]
        try:
            value = int(tokens[1])
        except ValueError:
            print("NON-NUMERIC ID IN {path}: {line}".format(path=path, line=line))
            return 1
        if key.startswith(RETIRED_PREFIX):
            holder = key[len(RETIRED_PREFIX):]
            if value in retired or value in ids.values():
                print("DUPLICATE ID {v} IN {path}".format(v=value, path=path))
                return 1
            retired[value] = holder
        else:
            if key in ids:
                print("DUPLICATE STRING {n} IN {path}".format(n=key, path=path))
                return 1
            if value in retired or value in ids.values():
                print("DUPLICATE ID {v} IN {path}".format(v=value, path=path))
                return 1
            ids[key] = value
            if 2 < len(tokens):
                names[key] = tokens[2]
        if value > highest:
            highest = value

    next_free = highest + 1
    return 0


def write_id_map(path):
    """Rewrite the map, retiring anything that no longer exists."""
    seen = set(harvested)
    for key in list(ids.keys()):
        if key not in seen:
            retired[ids[key]] = key
            del ids[key]

    entries = [(v, k, names.get(k, "")) for k, v in ids.items()]
    entries += [(k, RETIRED_PREFIX + v, "") for k, v in retired.items()]
    entries.sort()

    width = max([len(e[1]) for e in entries]) if entries else 1
    try:
        mapfile = open(path, "w")
        mapfile.write(MAP_HEADER)
        for value, key, who in entries:
            mapfile.write("{k:<{w}} {v:<5} {n}\n"
                          .format(k=key, w=width, v=value, n=who).rstrip() + "\n")
        mapfile.close()
    except Exception as e:
        print("ID map {path} could not be written: {e}".format(path=path, e=e))
        return 1
    return 0


def id_for(name, string):
    """The id this attribute must be given. Records the string as seen.

    Two C names that define the same string share the id, because the
    string is what the datastore keys on - see the note on "ids" above.
    """
    global next_free

    key = string.strip('"')
    harvested.append(key)
    # remember every name that defines this string; the first one wins
    # the map's comment column
    if key not in names:
        names[key] = name
    elif name not in names[key].split(","):
        names[key] = names[key] + "," + name
    if key in ids:
        return ids[key]
    if not assign_mode:
        # caller checks for missing strings before generating anything
        return -1
    ids[key] = next_free
    next_free += 1
    return ids[key]


class NullSink:
    """Swallows the generated text during the name-collecting pass."""

    def write(self, text):
        pass

    def close(self):
        pass


def harvest_constants(options, path, constants):
    # open the file
    try:
        inputfile = open(path, "r")
    except Exception as e:
        print("File {path} could not be opened: {e}"
              .format(path=path, e=e))
        return 1, 0

    # read the file - these files aren't too large
    # so ingest the whole thing at one gulp
    try:
        lines = inputfile.readlines()
    except Exception as e:
        print("Error reading file {path}: {e}"
              .format(path=path, e=e))
        inputfile.close()
        return 1, 0

    inputfile.close()  # we read everything, so done with the file

    firstline = True
    preamble = "                               \""
    linesize = 53
    # loop over the lines
    for n in range(len(lines)):
        line = lines[n]
        # remove white space at front and back
        myline = line.strip()
        # remove comment lines
        if "/*" in myline or "*/" in myline or myline.startswith("*"):
            continue
        # if the line starts with #define, then we want it
        if myline.startswith("#define"):
            value = myline[8:]
            # skip some well-known unwanted values
            if value.startswith("PMIx"):
                continue
            if value.startswith("PMIX_HAVE_VISIB"):
                continue
            if value.startswith("PMIX_LAUNCHER_RNDZ_FILE"):
                continue
            if value.startswith("PMIX_LAUNCHER_RNDZ_URI"):
                continue
            if value.startswith("PMIX_KEEPALIVE_PIPE"):
                continue
            tokens = value.split()
            if len(tokens) >= 2:
                if tokens[1][0] == '"':
                    if not firstline:
                        constants.write(",\n\n")
                    firstline = False
                    constants.write("    {.index = " + str(id_for(tokens[0], tokens[1])) + ", .name = \"" + tokens[0] + "\", .string = " + tokens[1])
                    # only one attribute violates the one-word rule for type
                    if tokens[0] == "PMIX_EVENT_BASE":
                        dstart = 3
                        datatype = "PMIX_POINTER"
                    elif tokens[0] == "PMIX_ATTR_UNDEF":
                        constants.write(", .type = PMIX_POINTER,\n     .description = (char *[]){\"NONE\", NULL}}")
                        continue
                    else:
                        dstart = 4
                        if tokens[3] == "(bool)":
                            datatype = "PMIX_BOOL"
                        elif tokens[3] == "(char*)":
                            datatype = "PMIX_STRING"
                        elif tokens[3] == "(pmix_rank_t)":
                            datatype = "PMIX_PROC_RANK"
                        elif tokens[3] == "(uint32_t)":
                            datatype = "PMIX_UINT32"
                        elif tokens[3] == "(int32_t)":
                            datatype = "PMIX_INT32"
                        elif tokens[3] == "(uint64_t)":
                            datatype = "PMIX_UINT64"
                        elif tokens[3] == "(int)":
                            datatype = "PMIX_INT"
                        elif tokens[3] == "(uint16_t)":
                            datatype = "PMIX_UINT16"
                        elif tokens[3] == "(pmix_data_array_t)" or tokens[3] == "(pmix_data_array_t*)":
                            datatype = "PMIX_DATA_ARRAY"
                        elif tokens[3] == "(pmix_proc_t*)":
                            datatype = "PMIX_PROC"
                        elif tokens[3] == "(pmix_coord_t*)":
                            datatype = "PMIX_COORD"
                        elif tokens[3] == "(pmix_coord_view_t)":
                            datatype = "PMIX_UINT8"
                        elif tokens[3] == "(float)":
                            datatype = "PMIX_FLOAT"
                        elif tokens[3] == "(pmix_byte_object_t)":
                            datatype = "PMIX_BYTE_OBJECT"
                        elif tokens[3] == "(hwloc_topology_t)":
                            datatype = "PMIX_POINTER"
                        elif tokens[3] == "(size_t)":
                            datatype = "PMIX_SIZE"
                        elif tokens[3] == "(pmix_data_range_t)":
                            datatype = "PMIX_UINT8"
                        elif tokens[3] == "(pmix_persistence_t)":
                            datatype = "PMIX_UINT8"
                        elif tokens[3] == "(pmix_scope_t)":
                            datatype = "PMIX_UINT8"
                        elif tokens[3] == "(pmix_status_t)":
                            datatype = "PMIX_STATUS"
                        elif tokens[3] == "(void*)":
                            datatype = "PMIX_POINTER"
                        elif tokens[3] == "(TBD)":
                            datatype = "TBD"
                        elif tokens[3] == "(time_t)":
                            datatype = "PMIX_TIME"
                        elif tokens[3] == "(struct" and tokens[4] == "timeval)":
                            datatype = "PMIX_TIMEVAL"
                            dstart = 5
                        elif tokens[3] == "(pmix_envar_t*)":
                            datatype = "PMIX_ENVAR"
                        elif tokens[3] == "(pid_t)":
                            datatype = "PMIX_PID"
                        elif tokens[3] == "(pmix_proc_state_t)":
                            datatype = "PMIX_PROC_STATE"
                        elif tokens[3] == "(pmix_link_state_t)":
                            datatype = "PMIX_LINK_STATE"
                        elif tokens[3] == "(pointer)":
                            datatype = "PMIX_POINTER"
                        elif tokens[3] == "(pmix_topology_t)" or tokens[3] == "(pmix_topology_t*)":
                            datatype = "PMIX_TOPO"
                        elif tokens[3] == "(pmix_cpuset_t)" or tokens[3] == "(pmix_cpuset_t*)":
                            datatype = "PMIX_PROC_CPUSET"
                        elif tokens[3] == "(pmix_geometry_t)" or tokens[3] == "(pmix_geometry_t*)":
                            datatype = "PMIX_GEOMETRY"
                        elif tokens[3] == "(pmix_device_distance_t)" or tokens[3] == "(pmix_device_distance_t*)":
                            datatype = "PMIX_DEVICE_DIST"
                        elif tokens[3] == "(pmix_endpoint_t)" or tokens[3] == "(pmix_endpoint_t*)":
                            datatype = "PMIX_ENDPOINT"
                        elif tokens[3] == "(pmix_device_type_t)":
                            datatype = "PMIX_DEVTYPE"
                        elif tokens[3] == "(varies)":
                            datatype = "PMIX_INT"
                        elif tokens[3] == "(pmix_storage_accessibility_t)":
                            datatype = "PMIX_UINT64"
                        elif tokens[3] == "(pmix_storage_medium_t)":
                            datatype = "PMIX_UINT64"
                        elif tokens[3] == "(pmix_storage_persistence_t)":
                            datatype = "PMIX_UINT64"
                        elif tokens[3] == "(pmix_storage_access_type_t)":
                            datatype = "PMIX_UINT16"
                        elif tokens[3] == "(double)":
                            datatype = "PMIX_DOUBLE"
                        elif tokens[3] == "(pmix_alloc_inheritance_t)":
                            datatype = "PMIX_ALLOC_INHERIT"
                        else:
                            print("UNKNOWN TOKEN: {tok}".format(tok=tokens[3]))
                            return 1
                    constants.write(", .type = " + datatype + ",\n     .description = (char *[]){\"")
                    # the description consists of at least all remaining tokens
                    m = dstart + 1
                    desc = tokens[dstart].replace("\"", "\\\"")
                    if "DEPRECATED" in desc:
                        constants.write(desc + "\"")
                        constants.write(", NULL}}")
                        continue
                    firstout = True
                    while m < len(tokens):
                        tmp = tokens[m].replace("\"", "\\\"")
                        if (len(tmp) + len(desc) + 1) > linesize:
                            if firstout:
                                constants.write(desc + "\"")
                            else:
                                constants.write(",\n" + preamble + desc + "\"")
                            firstout = False
                            desc = tmp
                        else:
                            desc += " " + tmp
                        m += 1
                    # if the next line starts with '/', then it is a continuation
                    # of the description
                    line = lines[n+1]
                    # remove white space at front and back
                    myline = line.strip()
                    while len(myline) > 0 and myline[0] == '/':
                        # step over until we see the beginning of text
                        m = 1
                        while myline[m] == '/' or myline[m] == ' ':
                            m += 1
                        # the rest of the line is part of the description
                        k = m
                        tmp = myline[k]
                        if tmp == '"':
                            tmp = "\\\""
                        k += 1
                        while k < len(myline):
                            while k < len(myline) and ' ' != myline[k]:
                                if myline[k] == '"':
                                    tmp += "\\\""
                                else:
                                    tmp += myline[k]
                                k += 1
                            if (len(tmp) + len(desc) + 1) > linesize:
                                if firstout:
                                    constants.write(desc + "\"")
                                else:
                                    constants.write(",\n" + preamble + desc + "\"")
                                firstout = False
                                desc = tmp
                            else:
                                if len(desc) > 0:
                                    desc += " " + tmp
                                else:
                                    desc = tmp
                            tmp = ""
                            k += 1
                        n += 1
                        line = lines[n+1]
                        myline = line.strip()
                    if len(desc) > 0:
                        if firstout:
                            constants.write(desc + "\"")
                        else:
                            constants.write(",\n" + preamble + desc + "\"")
                    # finish it up by closing the definition
                    constants.write(", NULL}}")

    inputfile.close()
    return 0


def _write_header(options, num_elements, boundary):
    contents = '''/*
 * This file is autogenerated by construct_dictionary.py.
 * Do not edit this file by hand.
 */

#include "src/include/pmix_config.h"
#include "src/include/pmix_globals.h"
#include "include/pmix_common.h"

#ifndef PMIX_DICTIONARY_H
#define PMIX_DICTIONARY_H

BEGIN_C_DECLS

PMIX_EXPORT extern const pmix_regattr_input_t pmix_dictionary[{ne}];

/* Number of entries in pmix_dictionary[]. This is what you iterate with;
 * it is NOT the same as PMIX_INDEX_BOUNDARY below, because ids are
 * append-only and retired ids leave gaps. */
#define PMIX_DICTIONARY_SIZE {ne}

/* One past the highest attribute id ever assigned, retired ones included.
 * Sizes anything indexed by id, and is where run-time (non-reserved) key
 * numbering starts, so that it cannot collide with a reserved id. */
#define PMIX_INDEX_BOUNDARY {nb}

END_C_DECLS

#endif\n
'''.format(ne=num_elements, nb=boundary)

    if options.dryrun:
        constants = sys.stdout
        outpath = None
    else:
        outpath = os.path.join(options.out, "pmix_dictionary.h")
        try:
            constants = open(outpath, "w+")
        except Exception as e:
            print("{outpath} CANNOT BE OPENED - DICTIONARY COULD NOT BE CONSTRUCTED: {e}"
                  .format(outpath=outpath, e=e))
            return 1
    constants.write(contents)
    constants.close()
    return 0


def harvest_all(args, constants):
    """Run both headers through the parser, writing to "constants"."""
    source_include_dir = os.path.join(args.root, "include")

    rc = harvest_constants(args,
                           os.path.join(source_include_dir, "pmix_common.h.in"),
                           constants)
    if 0 != rc:
        print("HARVEST PMIX_COMMON FAILED - DICTIONARY COULD NOT BE CONSTRUCTED")
        return 1
    constants.write(",\n")

    rc = harvest_constants(args,
                           os.path.join(source_include_dir, "pmix_deprecated.h"),
                           constants)
    if 0 != rc:
        print("HARVEST PMIX_DEPRECATED FAILED - DICTIONARY COULD NOT BE CONSTRUCTED")
        return 1
    return 0


def main():
    global assign_mode
    global harvested

    parser = argparse.ArgumentParser(description="Generate attribute dictionary.")
    parser.add_argument("--root",
                        required=True,
                        help="Root directory of code tree")
    parser.add_argument("--out",
                        required=True,
                        help="Output C file")
    parser.add_argument("--ids",
                        default=None,
                        help="Attribute id map (default: contrib/dictionary_ids.txt "
                             "under --root)")
    parser.add_argument("--update-ids",
                        action="store_true",
                        help="Assign ids to new attributes and rewrite the id map. "
                             "Run this when you add or remove an attribute, and "
                             "commit the result.")
    parser.add_argument("--dryrun",
                        action="store_true",
                        help="Do not write out resulting file")

    args = parser.parse_args()

    idpath = args.ids
    if idpath is None:
        idpath = os.path.join(args.root, "contrib", "dictionary_ids.txt")

    if 0 != load_id_map(idpath):
        return 1

    # First pass: find out which attributes exist, without writing
    # anything. An attribute with no id must stop the build BEFORE a
    # half-written dictionary lands, and --update-ids has to know the
    # whole set before it can retire what is gone.
    assign_mode = args.update_ids
    harvested = []
    if 0 != harvest_all(args, NullSink()):
        return 1

    missing = [n for n in harvested if n not in ids]
    missing = [names.get(n, n) + "  (" + n + ")" for n in sorted(set(missing))]
    if missing:
        print("\n".join([
            "",
            "ATTRIBUTE(S) WITH NO ASSIGNED ID:",
            "",
        ] + ["    " + n for n in missing] + [
            "",
            "Attribute ids are append-only and are recorded in",
            "    " + idpath,
            "so that they stay the same across releases. Assign ids to the",
            "attributes above, and commit the result alongside your header",
            "change, by running:",
            "",
            "    make update-dictionary",
            "",
        ]))
        return 1

    if args.update_ids and not args.dryrun:
        if 0 != write_id_map(idpath):
            return 1

    # Second pass: generate for real, now that every name has an id.
    harvested = []

    if args.dryrun:
        constants = sys.stdout
        outpath = None
    else:
        outpath = os.path.join(args.out, "pmix_dictionary.c")
        try:
            constants = open(outpath, "w+")
        except Exception as e:
            print("{outpath} CANNOT BE OPENED - DICTIONARY COULD NOT BE CONSTRUCTED: {e}"
                  .format(outpath=outpath, e=e))
            return 1

    # write the source file
    constants.write("""/*
 * This file is autogenerated by construct_dictionary.py.
 * Do not edit this file by hand.
 */

#include "src/include/pmix_dictionary.h"

const pmix_regattr_input_t pmix_dictionary[] = {
""")

    # scan across the header files in the src directory
    # looking for constants and typedefs
    if 0 != harvest_all(args, constants):
        constants.close()
        if outpath:
            os.remove(outpath)
        return 1

    # mark the end of the array
    constants.write("""\n};""")
    constants.write("\n")
    constants.close()

    # The array holds one entry per live attribute; the boundary has to
    # clear every id ever handed out, retired ones included, so that
    # run-time key numbering starts above all of them.
    boundary = max(list(ids.values()) + list(retired.keys())) + 1

    # write the header
    return _write_header(args, len(harvested), boundary)


if __name__ == '__main__':
    exit(main())
