sudo: false
dist: xenial

cache:
  apt: true

env:
  global:
    # TODO: -fsanitize=address -fsanitize=undefined
    - CFLAGS="-Wall -Wextra -Werror -Wno-unused-function"
    - CXXFLAGS="-Wall -Wextra -Werror -Wno-unused-function"

addons:
  apt:
    packages:
      - gfortran
      - perl
      - libevent-dev

jobs:
  fast_finish: true
  include:
    - script:
        - ./autogen.pl
        - ./configure
        - make all
        - make check
