/*
 * Copyright (c) 2018-2020 Cisco Systems, Inc.  All rights reserved
 * Copyright (c) 2019-2020 Intel, Inc.  All rights reserved.
 * Copyright (c) 2021-2026 Nanook Consulting  All rights reserved.
 * $COPYRIGHT$
 *
 * Additional copyrights may follow
 *
 * $HEADER$
 */

#include "pmix_config.h"

#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#ifdef HAVE_STRING_H
#    include <string.h>
#endif

#include "src/util/pmix_string_copy.h"

void pmix_string_copy(char *dest, const char *src, size_t dest_len)
{
    size_t i;
    char *new_dest = dest;

    // PMIx does not do *giant* string copies.  Hence, we use the
    // heuristic: if "dest_len" is too large, this is a programmer
    // error.  We pseudo-arbitrarily pick a large value to be the max
    // allowable dest_len: 128K.  If we ever need to increase this
    // value someday (because something has a legit reason to
    // pmix_string_copy() more than 128K), the core dumps that are
    // generated by the assert() failure should make this fairly
    // obvious.
    assert(dest_len <= PMIX_MAX_SIZE_ALLOWED_BY_PMIX_STRING_COPY);

    // A zero-length destination buffer has no room for even the
    // terminating '\0'.  Do nothing rather than write to dest[-1].
    if (0 == dest_len) {
        return;
    }

    for (i = 0; i < dest_len; ++i, ++src, ++new_dest) {
        *new_dest = *src;
        if ('\0' == *src) {
            return;
        }
    }

    dest[dest_len - 1] = '\0';
}

char *pmix_getline(FILE *fp, bool *failed)
{
    char *line = NULL, *grown;
    size_t len = 0, size = 0;
    bool started = false;
    int c;

    if (NULL != failed) {
        *failed = false;
    }

    /* a character at a time, to the newline however far away it is */
    for (;;) {
        c = getc(fp);
        if (EOF == c) {
            if (ferror(fp)) {
                /* not the end of the stream: whatever is left of it was
                 * never read, so this fragment is not the line */
                goto fail;
            }
            /* a final line with no newline is still a line */
            break;
        }
        started = true;
        if ('\n' == c) {
            break;
        }
        if ('\0' == c) {
            /* handed back as a C string, the rest of the line would
             * silently vanish */
            goto fail;
        }
        /* room for this character and the terminator after it */
        if (len + 2 > size) {
            size = (0 == size) ? 256 : 2 * size;
            grown = (char *) realloc(line, size);
            if (NULL == grown) {
                goto fail;
            }
            line = grown;
        }
        line[len++] = (char) c;
    }

    if (!started) {
        /* the end of the stream, with nothing at all on this line */
        return NULL;
    }
    if (NULL == line) {
        /* an empty line is still a line */
        line = strdup("");
        if (NULL == line) {
            goto fail;
        }
        return line;
    }
    line[len] = '\0';
    return line;

fail:
    free(line);
    if (NULL != failed) {
        *failed = true;
    }
    return NULL;
}
