# -*- makefile -*-
#
# Copyright (c) 2016      Intel, Inc.  All rights reserved.
# Copyright (c) 2021-2025 Nanook Consulting  All rights reserved.
# $COPYRIGHT$
#
# Additional copyrights may follow
#
# $HEADER$

EXTRA_DIST += hwloc/help-ploc.txt

headers += \
        hwloc/pmix_hwloc.h

sources += \
        hwloc/pmix_hwloc.c \
        hwloc/pmix_hwloc_datatype.c
