.\" Automatically generated by Pandoc 2.14.2
.\"
.TH "pattrs" "1" "" "2021-08-17" "Open PMIx"
.hy
.SH NAME
.PP
pattrs - Print supported attributes at the client, server, and host
levels
.SH SYNOPSIS
.IP
.nf
\f[C]
pattrs [ options ]
\f[R]
.fi
.SH DESCRIPTION
.PP
\f[C]pattrs\f[R] will print a list of the supported PMIx APIs and the
supported PMIx attributes for each PMIx API at each of the client,
server, and host levels.
Host level information requires that \f[C]pattrs\f[R] connect to an
appropriate server - the tool will automatically attempt to do so, but
options are provided to assist its search or to direct it to a specific
server.
.SH OPTIONS
.PP
\f[C]pattrs\f[R] supports the following options:
.IP
.nf
\f[C]
-c|--client <arg0>       Comma-delimited list of client function whose
                         attributes are to be printed (function or all)
   --client-fns          List the functions supported in this client
                         library
-h|--help                This help message
-h|--host <arg0>         Comma-delimited list of host function whose
                         attributes are to be printed (function or all)
   --host-fns            List the functions supported by this host
                         environment
-n|--nspace <arg0>       Specify server nspace to connect to
-p|--pid <arg0>          Specify server pid to connect to
-s|--server <arg0>       Comma-delimited list of server function whose
                         attributes are to be printed (function or all)
   --server-fns          List the functions supported in this server
                         library
   --system-server       Specifically connect to the system server
   --system-server-first Look for the system server first
-t|--tool <arg0>         Comma-delimited list of tool function whose
                         attributes are to be printed (function or all)
   --tool-fns            List the functions supported in this tool library
   --uri <arg0>          Specify URI of server to connect to
-v|--verbose             Be Verbose
\f[R]
.fi
.SH AUTHORS
.PP
The OpenPMIx maintainers \[en] see https://github.com/openpmix/openpmix
or the file \f[C]AUTHORS\f[R].
