.\" Automatically generated by Pandoc 2.14.2
.\"
.TH "pevent" "1" "" "2021-08-17" "Open PMIx"
.hy
.SH NAME
.PP
pevent - Generate an event and inject it into the system
.SH SYNOPSIS
.IP
.nf
\f[C]
pevent [ options ]
\f[R]
.fi
.SH DESCRIPTION
.PP
\f[C]pevent\f[R] will generate a specified event and inject it into a
server.
This requires that \f[C]pevent\f[R] connect to an appropriate server -
the tool will automatically attempt to do so, but options are provided
to assist its search or to direct it to a specific server.
.SH OPTIONS
.PP
\f[C]pevent\f[R] supports the following options:
.IP
.nf
\f[C]
-e|--event               Status code of event to be sent
-h|--help                This help message
-p|--pid <arg0>          Specify starter pid
-r|--range               Range of event to be sent
-v|--verbose             Be Verbose
\f[R]
.fi
.SH AUTHORS
.PP
The OpenPMIx maintainers \[en] see https://github.com/openpmix/openpmix
or the file \f[C]AUTHORS\f[R].
