.\" Automatically generated by Pandoc 2.14.2
.\"
.TH "plookup" "1" "" "2021-08-17" "Open PMIx"
.hy
.SH NAME
.PP
plookup - Request the value of one or more keys
.SH SYNOPSIS
.IP
.nf
\f[C]
plookup [ options ] [ keys ]
\f[R]
.fi
.SH DESCRIPTION
.PP
\f[C]plookup\f[R] will request the value of the specified keys.
This requires that \f[C]plookup\f[R] connect to an appropriate server -
the tool will automatically attempt to do so, but options are provided
to assist its search or to direct it to a specific server.
Reserved keys must be provided in their string form - e.g.,
\[lq]pmix.job.term.status\[rq] as opposed to the key\[cq]s name of
\[lq]PMIX_JOB_TERM_STATUS\[rq].
.SH OPTIONS
.PP
\f[C]plookup\f[R] supports the following options:
.IP
.nf
\f[C]
-h|--help                This help message
-p|--pid <arg0>          Specify starter pid
-t|--timeout             Max number of seconds to wait for data to become
                         available
-v|--verbose             Be Verbose
-w|--wait                Wait for data to be available
\f[R]
.fi
.SH AUTHORS
.PP
The OpenPMIx maintainers \[en] see https://github.com/openpmix/openpmix
or the file \f[C]AUTHORS\f[R].
