.\" Automatically generated by Pandoc 2.14.2
.\"
.TH "pmixcc" "1" "" "2021-08-22" "Open PMIx"
.hy
.SH NAME
.PP
pmix_wrapper - Back-end PMIx wrapper command
.SH SYNOPSIS
.IP
.nf
\f[C]
pmix_wrapper [options]
\f[R]
.fi
.SH DESCRIPTION
.PP
\f[C]pmix_wrapper\f[R] is not meant to be called directly by end users.
It is automatically invoked as the back-end by the PMIx wrapper command
\f[C]mpicc.\f[R]
.PP
Some PMIx installations may have additional wrapper commands, and/or
have renamed the wrapper compilers listed above to avoid executable name
conflicts with other PMIx implementations.
.SH SEE ALSO
.PP
The following may exist depending on your particular PMIx installation:
\f[C]pmixcc\f[R](1) and the website at https://pmix.org/.
.SH AUTHORS
.PP
The PMIx maintainers \[en] see https://pmix.org/ or the file AUTHORS.
.PP
This manual page was originally contributed by Dirk Eddelbuettel
<edd@debian.org>, one of the Debian GNU/Linux maintainers for Open MPI,
and may be used by others.
