.\" Automatically generated by Pandoc 2.14.2
.\"
.TH "pps" "1" "" "2021-08-17" "Open PMIx"
.hy
.SH NAME
.PP
pps - Request the status of one or more namespaces and/or nodes
.SH SYNOPSIS
.IP
.nf
\f[C]
pps [ options ]
\f[R]
.fi
.SH DESCRIPTION
.PP
\f[C]pps\f[R] will request the status of the specified namespaces and/or
nodes.
If no namespace or node is given, then \f[C]pps\f[R] will request the
status of all running jobs.
This requires that \f[C]pps\f[R] connect to an appropriate server - the
tool will automatically attempt to do so, but options are provided to
assist its search or to direct it to a specific server.
.SH OPTIONS
.PP
\f[C]pps\f[R] supports the following options:
.IP
.nf
\f[C]
-h|--help                This help message
-n|--nodes               Display Node Information
   --nspace              Nspace of job whose status is being requested
-p|--pid <arg0>          Specify pid of starter to be contacted (default is
                         to system server
   --parseable           Provide parseable output
\f[R]
.fi
.SH AUTHORS
.PP
The OpenPMIx maintainers \[en] see https://github.com/openpmix/openpmix
or the file \f[C]AUTHORS\f[R].
