.\" Automatically generated by Pandoc 2.14.2
.\"
.TH "pquery" "1" "" "2021-08-17" "Open PMIx"
.hy
.SH NAME
.PP
pquery - Request information from the system
.SH SYNOPSIS
.IP
.nf
\f[C]
pquery [ options ] [ keys ]
\f[R]
.fi
.SH DESCRIPTION
.PP
\f[C]pquery\f[R] will request and output the specified information.
This requires that \f[C]pquery\f[R] connect to an appropriate server -
the tool will automatically attempt to do so, but options are provided
to assist its search or to direct it to a specific server.
.PP
Keys passed to \f[C]pquery\f[R] may optionally include one or more
qualifiers, with the individual qualifiers delimited by semi-colons.
For example:
.IP
.nf
\f[C]
PMIX_STORAGE_XFER_SIZE[PMIX_STORAGE_ID=lustre1,lustre2;PMIX_STORAGE_PATH=foo]
\f[R]
.fi
.SH OPTIONS
.PP
\f[C]pquery\f[R] supports the following options:
.IP
.nf
\f[C]
-h|--help                This help message
-n|--nspace <arg0>       Specify server nspace to connect to
-p|--pid <arg0>          Specify server pid to connect to
   --system-server       Specifically connect to the system server
   --system-server-first Look for the system server first
   --uri <arg0>          Specify URI of server to connect to
-v|--verbose             Be Verbose
\f[R]
.fi
.SH AUTHORS
.PP
The OpenPMIx maintainers \[en] see https://github.com/openpmix/openpmix
or the file \f[C]AUTHORS\f[R].
