#-----------------------------------------------------------------
# File: python-bindings.yaml
#
# Descr: Tests for PMIx Python bindings across different python versions.
#        Uses common actions to reduce repetition in this file.
#
# See also: .github/actions/build-python-bindings/action.yaml)
#-----------------------------------------------------------------
name: OpenPMIx-bindings Python Versions

on: [pull_request]

jobs:
  build-py39:
    name: CPython 3.9
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-python-bindings
        with:
          python-version: 3.9

  build-py310:
    name: CPython 3.10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-python-bindings
        with:
          python-version: 3.10

  build-py311:
    name: CPython 3.11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-python-bindings
        with:
          python-version: 3.11

  build-py312:
    name: CPython 3.12
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-python-bindings
        with:
          python-version: 3.12

  build-py313:
    name: CPython 3.13
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build-python-bindings
        with:
          python-version: 3.13

###
# TJN: Ignore PyPy implementation versions for now, but add
#      example block here in case add in future.
#  build-pypy310:
#    name: PyPy 3.10
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - uses: ./.github/actions/build-python-bindings
#        with:
#          python-version: pypy3.10
###
